### ISSUE TITLE
Keycloak: Unable to update account

### ISSUE THREAD

**Issue by MarcelCoding** [dd-ix/nix-config#39]
Unable to change password, configure 2fa ...

Console output with debug logging:
```
Nov 08 20:23:37 mno001 keycloak-start[2207000]: 2023-11-08 20:23:37,891 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-61) Error response 403: org.keycloak.services.ForbiddenException
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.keycloak.services.managers.Auth.requireOneOf(Auth.java:91)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.keycloak.services.resources.account.AccountRestService.account(AccountRestService.java:141)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at java.base/java.lang.reflect.Method.invoke(Method.java:578)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:192)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Nov 08 20:23:37 mno001 keycloak-start[2207000]:         at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by MarcelCoding** [comment]
keycloak isn't existing anymore
